"""Design-first third iteration; concrete sonic scores precede generation requests."""
import json,copy,hashlib
from pathlib import Path
root=Path(__file__).resolve().parents[2];folder=root/'tools/sfx'
d=json.loads((folder/'reviews/current_disposition.json').read_text());old=json.loads((folder/'rework27_naval_20260930_v2.json').read_text());lookup={a['id']:a for a in old['assets']}
# id: duration target, source duration, audible score, English model instruction, listening contrast
scores={
'W13b':(1.2,2,'0–80ms厚重炮弹撞击；80–350ms大面积装甲低频震动；350–1200ms短促钢结构碎震衰减。主体是重冲击，细金属只作尾层。','A heavy naval artillery shell slams into a massive steel battleship armor plate above the ocean. One forceful broad impact, a deep chesty structural shock, then a brief irregular rumble of thick steel flexing. Heavy low-mid body dominates, tiny metal fragments remain secondary. Exterior open-air decay. About one second. No thin wire twang, pliers, drum, bell or ringing anvil.','与轻受击相比体量更大；不能像夹铁丝、敲鼓。'),
'A03':(1.1,2,'0–100ms低权重投弹解脱；100–900ms低到中频的空气撕裂向远处下坠；尾端快速离开。投放轨迹主导，不能只剩按钮声。','A heavy anti-ship bomb drops away from a carrier bomber flying over open ocean. A brief solid release thud leads immediately into a falling-air rush, a smooth descending whistle receding rapidly below the aircraft. The falling motion dominates over the release hardware. One second, rounded air tone, no explosion, splash, siren or cartoon slide whistle.','与飞机巡航不同：一次明确远离下坠；没有虚构命中。'),
'S01':(2.0,3,'0–400ms宽厚海水盖过舰体；400–1400ms大体积水层下压、低沉空气团逸出；1400–2000ms水面高频逐渐退去。','A steel submarine hull submerges beneath deep open ocean. A broad heavy sheet of seawater washes over the hull, a deep rolling water surge presses downward, then a few large low bubbling air pockets escape. The surface wash fades into submerged depth. Two-second large-volume water movement, natural spacious low-mid body. No sink, faucet, trickling stream, tiny droplets or radio filter.','整体由明到暗、由表面到深处；不是洗手台咕噜。'),
'S02':(2.0,3,'0–600ms低沉水体鼓起；600–1200ms宽幅破面；1200–2000ms大片海水从钢制舰体滑落，留下开阔空气。','A steel submarine hull rises through deep open ocean and breaks the surface. A deep swelling water displacement grows into one broad surface breach, then heavy sheets of seawater drain off the hull into the sea. Two seconds, large rounded water mass and open-air finish. No faucet, sink, beach trickle, bubbles-only recording or explosion.','与下潜的方向相反：由闷到开阔，破面后排水。'),
'K01':(.55,1,'0–120ms柔和低频蓄势；120–320ms短上扬能量轮廓；320–550ms圆润单一落点。用于舰娘技能成功，不模仿具体武器。','A stylized anime naval tactical ability activation cue: a short warm low energy swell rises smoothly and resolves into one rounded clear midrange pulse. Confident release of a shipgirl gun-rig ability, about half a second. Clean controlled synthesized sound, no mechanical clicking, magic sparkle, sharp treble, melody or explosion.','比普通命令更有起势；一次成功感，不是机关开锁。'),
'N10':(.35,1,'两枚同音高短音，前短后略长，间隔约70ms；中低频、低优先级。阶段推进只提示一次，不做奖励。','A naval tactical map stage-update earcon. Two soft clean mid-low electronic tones at the same pitch, a short first pulse and slightly longer second pulse, separated by a small gap. Dry, warm, about one third of a second. No click, static, noise, melody, alarm or rising fanfare.','与完成的上行解决感不同；与排队的双触点材质不同。'),
'N11a':(.65,1,'三个柔和有音高落点，低→中→高，末音比前两音长；短三度/五度式明朗收束，尾音快速消退。','A restrained naval mission-success earcon, three warm clean rounded tonal notes rising to a consonant resolved final note. The first two notes are brief, the last gently sustains then fades; total about two thirds of a second. Elegant anime tactical UI, no full music, fanfare, mechanical noise, harsh buzz or glittering high bells.','成功结束而非警报；允许短音型，不再用机械噪声替代。'),
'F04':(.7,1,'柔和低沉靠稳触感后，单枚短暖提示确认“已靠泊”；物理层轻、确认层清楚，避免绳索摩擦成为主体。','A naval docking-complete cue: one soft low cushioned hull settling thump followed by one short warm clear confirmation tone. A shipgirl has safely settled against a supply pontoon. Compact calm completion, less than a second, no rope squeaks, grinding, scraping, collision crash or background water.','应听出“停稳完成”；不靠无法辨认的绳索声。'),
'F05a':(1.0,2,'0–150ms柔和接通；150–700ms低沉平滑的液泵启动；700–1000ms短稳定流动后收束，不留嘶声。','A naval tender starts transferring fuel to a docked shipgirl rig. A soft connection thump followed by a smooth low liquid-pump onset and brief enclosed fluid movement, fading quickly. Warm clean low-mid texture, about one second. No hiss, static, rattling machinery, faucet, harsh coupling click or continuous ambience.','只表达开始输送；不是长底噪。'),
'F09a':(.9,2,'低沉重物滚向投放口＋短链条放出，随向下空气感结束；重物和方向主导，保险开关不作主体。','A heavy spherical naval sea mine starts rolling from a shipboard deployment cradle toward the stern chute over the ocean. A short weighty rounded metal roll, low chain payout and a brief downward air movement. About one second, marine equipment carrying a heavy object. No factory switch, door latch, motor drone, explosion or impact in water yet.','应是有重量的布雷准备/投放动作；开始事件不提前伪造水雷完成。'),
'F09b':(.65,1,'短低音转一枚稳定中音，间隔清晰；表示布雷作业完成，不补一枚并不存在的新水雷入水。','A naval minelaying-operation complete signal on a tactical chart. A short low warm tone followed by a steady rounded middle tone that ends firmly, about half a second. Calm work-complete acknowledgment with a subtle deep body. No mine explosion, extra water splash, mechanical switch, noise, siren or melody.','完成提示与重物运动的开始声对照；不能凭音频增加投放事实。'),
'U02':(.22,1,'两枚柔和短音高→低，后一音更轻；极短回退，干净无摩擦尾层。','A naval tactical-menu back earcon. Two tiny clean rounded tones stepping downward, second softer, total about two tenths of a second. Gentle retreat and cancellation, quiet and dry. No mechanical slide, thump, gritty texture, static, error buzzer or music.','与已采纳U01确认方向相反；不是拒绝报警。'),
'U04a':(.22,1,'单枚清楚的圆润短音，微小上挑、立即止住；不加气流滑动或金属底层。','A naval fleet-course command accepted earcon. One clean warm short rounded tone with a tiny upward pitch inflection and an immediate gentle ending. About two tenths of a second. Precise positive acknowledgment on a sea-chart interface. No air whoosh, hiss, static, click, machinery or music.','单音立即执行，与已选排队双触点区分。'),
'U04c':(.3,1,'两枚短而收紧的同音高中频脉冲，第二枚略实；表达注意力集中，频谱集中且不尖。','A naval fire-control focus-target confirmed earcon. Two clean centered midrange pulses at the same pitch, the second slightly firmer and shorter, ending decisively. About three tenths of a second, concentrated and controlled. No gunshot, explosion, mechanical lock, radar sweep, noise or music.','双脉冲收束，与移动的单上挑、排队轻触点不同。'),
'U06':(.4,1,'舰炮弹种选择确认：中低音短双音，第二音向侧档移动的音高跳变，配极轻低频重量；非装填动作。','A large naval gun ammunition-type selection earcon on a fleet gunnery display. Two compact low-mid clean rounded tones, a discrete pitch step between them and a restrained low weight under the second. Less than half a second. This confirms shell selection, not weapon loading. No rifle bolt, magazine, cartridge rattle, gunfire, mechanical click or music.','避免枪械装填；弹种选择不是已完成装填。'),
'U07a':(.25,1,'两枚同材质柔和音低→中，后音清楚、止住；开启与关闭共用频段和响度。','A naval tactical-assistance enabled earcon. Two soft pure rounded tones, low then middle, equal gentle loudness, brief gap and clean ending within a quarter second. Calm clear on-state. No physical switch, hiss, mechanical noise, sparkle or melody.','开启稳定上行；必须和U07b配对试听。'),
'U07b':(.25,1,'与开启相反的中→低双音，时长和音色一致；尾音不做报警颤动。','A naval tactical-assistance disabled earcon. Two soft pure rounded tones, middle then low, equal gentle loudness, brief gap and clean ending within a quarter second. Same warm tone family as enable, clear off-state. No physical switch, hiss, mechanical noise, alarm or melody.','关闭稳定下行；不能只换随机种子。'),
'U11':(.18,1,'极轻圆润单音快速展开后消失，低于命令提示约6dB；无需实际滑轨。','An extremely quiet naval tactical-panel opening UI cue. A tiny soft rounded tonal bloom appears and fades rapidly, under two tenths of a second. Delicate neutral low-mid tone, understated interface motion. No rail, scraping, whoosh, hiss, clatter, notification bell or music.','仅辅助面板出现，不抢操作和战斗注意力。')}
assert set(scores)=={x['id'] for x in d['items'] if x['status'] in ('revise_timbre','redesign_semantics')}
b=copy.deepcopy(old);b.update(id='sfx_design18_20261001_v3',assets=[],requirements=d['requirements'],cancelled=d['cancelled_asset_ids'],parent_batches=[old['id']],revision_reason='参考成熟游戏设计原则，重做体量与可学习音型；先设计后生成')
request={'batch_id':b['id'],'sounds':[]};lines=['# 第三轮音效设计：体量、动作与声音语义','','## 参考依据与本项目转译','','- [World of Warships 12.7](https://wiki.worldofwarships.com/Ship:Update_12.7)：分别处理火炮、命中舰船/水体及距离听感，并按重要性突出声音。这里采用“介质/体量/优先级”的设计原则，不复制现成音频。','- [Overwatch: Play by Sound，开发者GDC演讲](https://media.gdcvault.com/gdc2016/Presentations/Lawlor_Neumann_Overwatch_Play_by_Sound.pdf)：空间与分层、清楚玩法提示、稳定声音身份。这里转译为可学习的短音型及较小变体，不让三候选变成三个事件。','','以上是文字/演讲材料调研，不宣称已实际游玩或试听其资产。下列时间、音型和材质均为本项目设计。','','## 本轮纠偏','','真实声源要有体量：舰装受击不能只留高频小五金，潜艇水声必须是宽厚海水运动。指令/状态没有天然物理声源，采用短音型明确反馈，不强行让菜单变成机械车间。“二次元”落实为干净轮廓、温暖音高与紧凑衰减；“海战”落实为炮弹/舰装/压载/投雷等动作和尺度，不能指望模型理解游戏名称。提示型声音不是现实世界中可推导的语言，需要在实际画面中建立稳定关联。','','本轮新增采纳7项（W01 C、W02 B、W09 A、W10a B、N13 C、F02 A、U04b B），取消F11a/F11b。累计43项采用、61项取消（含先前N04），18项重新设计。','','## 分层与验收','','物理声mono、耳标stereo居中；提示不得生成额外开火/命中事实。每组三候选保持相同时序语义，仅调整主体厚度或圆润度。U11较命令声降低6dB。时长是编辑目标而非模型保证；保留源与自动裁静音版，长尾单列。首轮对比先不看标题辨认动作/方向，再结合画面判断；与近邻事件混淆、重复10次刺耳、出现人声/噪音即不通过。不得仅凭峰值/生成成功关闭问题。','','## 逐条声音设计','','| ID | 目标秒数 | 声音结构 | 对照验收 |','|---|---:|---|---|']
for i,(aid,(target,seconds,score,prompt,contrast)) in enumerate(scores.items()):
 a=copy.deepcopy(lookup[aid]);a.update(target_seconds=target,generation_seconds=seconds,direction=score+' 验收：'+contrast,english_brief=prompt,candidates=[],review_target_rms_dbfs=-30 if aid=='U11' else -24 if a['category'] in ('ui','skill','alert') else -23);a.pop('naval_context',None)
 for j,(label,variant) in enumerate([('清楚轮廓','Clear compact attack, dry and precisely separated stages.'),('温暖主体','Slightly warmer lower body; preserve all rhythmic and directional cues.'),('圆润边缘','Gentler upper frequencies and rounded attack; preserve the same sequence and direction.')]):
  cid=f'{aid}_d3_{"abc"[j]}';p=prompt+' '+variant+' Isolated finished game sound effect, no speech or vocals, no background ambience.';c=dict(id=cid,seed=202610011000+i*10+j,variation=label,prompt=p,status='planned');a['candidates'].append(c);request['sounds'].append(dict(id=cid,seed=c['seed'],prompt=p,seconds=seconds))
 b['assets'].append(a);lines.append(f'| {aid} {a["title"]} | {target} | {score} | {contrast} |')
lines+=['','## 生成交付','','设计先保存，再提交GPU。完整英文描述、seed及后期设置见 `design18_20261001_v3.json`；本轮18×3=54条。模型不保证音程、时序和体量准确，必须经新一轮听审。','']
(folder/'design18_20261001_v3.md').write_text('\n'.join(lines))
for name,obj in [('design18_20261001_v3.json',b),('design18_request_20261001_v3.json',request)]:
 p=folder/name;t=json.dumps(obj,ensure_ascii=False,indent=2)+'\n'
 if p.exists():assert p.read_text()==t
 else:p.write_text(t)
print('Design saved:18 assets /54 candidates')
